version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.maven.wagon:wagon-ssh
    versions:
    - 3.4.2
  - dependency-name: org.apache.maven.wagon:wagon-provider-api
    versions:
    - 3.4.2
  - dependency-name: org.apache.maven.wagon:wagon-http
    versions:
    - 3.4.2
  - dependency-name: org.apache.maven.wagon:wagon-file
    versions:
    - 3.4.2
